spring:
  application:
    name: turbotax-refund-status-service

server:
  port: 7001
  error:
    include-message: always

app:
  filing-metadata-service:
    host: localhost
    port: 7002
  ai-refund-eta-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG

