spring:
  application:
    name: turbotax-ai-refund-eta-service

server:
  port: 7003
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG

app:
  filing-query-service:
    host: localhost
    port: 7001