spring:
  application:
    name: turbotax-refund-status-aggregate-service

server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    name: logs/turbotax-refund-aggregation-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30