spring:
  application:
    name: turbotax-filinginfo-service

server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    name: logs/turbotax-filinginfo-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
