spring:
  application:
    name: turbotax-filinginfo-service

server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    name: /home/mgarg/projects/intuit/logs/turbotax-filing-query-service.log
