spring:
  application:
    name: turbotax-api-contracts

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30