spring:
  application:
    name: turbotax-refundstatus-service

server:
  port: 8001
  error:
    include-message: always

app:
  filing-metadata-service:
    host: localhost
    port: 7001  
  refund-status-aggregator-service:
    host: localhost
    port: 7002   
  ai-refund-eta-service:
    host: localhost
    port: 7003
  refund-prediction-service:
    url: https://refundprediction-ldyuo.eastus2.inference.ml.azure.com/score
    api-key: C0Hy78S1HZ25W0krtu78t6BmnVSmH2PN4fUuJ43yxGwvomK2xUEjJQQJ99BKAAAAAAAAAAAAINFRAZMLmfoq


logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG

