spring:
  application:
    name: turbotax-refundstatus-service
  config:
    import: application-secrets.yml

server:
  port: 8001
  error:
    include-message: always

app:
  filing-metadata-service:
    host: localhost
    port: 7001
  refund-status-aggregator-service:
    host: localhost
    port: 7002
  refund-prediction-service:
    url: https://refundprediction-ldyuo.eastus2.inference.ml.azure.com/score
    api-key: ${app.refund-prediction-service.api-key}

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    name: /home/mgarg/projects/intuit/logs/turbotax-refund-query-service.log
