spring:
  application:
    name: turbotax-refund-query-service

server:
  port: 7000
  error:
    include-message: always

app:
  filing-query-service:
    host: localhost
    port: 7001
  refund-aggregation-service:
    host: localhost
    port: 7002
  refund-prediction-service:
    url: https://refundprediction-hjraw.eastus2.inference.ml.azure.com/score
    api-key: Ay9WbYJqjhyJw2wp7dG4hAYl3YJtpCBmkTOWuX1nStX4a1PJClkYJQQJ99BLAAAAAAAAAAAAINFRAZML1Yz1

logging:
  level:
    root: INFO
    com.intuit.turbotax: DEBUG
  file:
    name: /home/mgarg/projects/intuit/logs/turbotax-refund-query-service.log
